### PR TITLE
Update phraser index.js

### PR DESCRIPTION
**Pull request by BadNintendo**
### Changes and Improvements

1. **Use of `Map` for Balance Changes**: - **Original Code**: Used a plain object (`{}`) for storing balance changes. - **Updated Code**: Uses a `Map` object for balance changes. - **Reason**: Using `Map` provides better performance for scenarios involving frequent additions and removals of keys. It also avoids potential issues with object prototype chain in JavaScript. - **Improvement**: Enhances performance and reliability when processing large numbers of transactions and operations.

2. **Refactoring of `skipOperation` Method**: - **Original Code**: Included several conditions in a single if statement. - **Updated Code**: Broke down the conditions into separate checks for clarity and added detailed logging for each condition. - **Reason**: Improves readability and maintainability of the code. Detailed logging helps in debugging and understanding the flow of data. - **Improvement**: Makes the code easier to understand and maintain, especially for developers unfamiliar with the project.

3. **Enhanced Serialization of Accounts and Currencies**: - **Original Code**: Performed hashing directly within the loop. - **Updated Code**: Abstracted hashing into the `getSerializedKey` function. - **Reason**: Encapsulates the logic for creating keys, which can be reused elsewhere in the application without duplicating code. - **Improvement**: Reduces code duplication and centralizes the serialization logic for accounts and currencies, making the system easier to update and maintain.

4. **Introduction of `getAdjustedAmount` and `OperationGroup`**: - **Original Code**: Adjusted amounts directly in the balance changes computation. - **Updated Code**: Introduced a method `getAdjustedAmount` to handle amount adjustments, especially when a block is orphaned. - **Reason**: Separates the concerns of amount calculation from the balance changes logic, adhering to the single responsibility principle. - **Improvement**: Makes the code modular and easier to manage. It also simplifies testing since the amount adjustment logic can be tested independently.

5. **Sorting and Grouping Operations**: - **Original Code**: Basic grouping logic without consideration for operation relationships. - **Updated Code**: Enhanced the grouping logic to account for related operations, ensuring they are processed together. - **Reason**: Ensures that operations that are logically connected are handled in a consistent manner. - **Improvement**: Increases the accuracy of operation processing and the integrity of the resultant data, particularly in complex transaction scenarios.

6. **Error Handling and Custom Errors**: - **Original Code**: Limited error handling capabilities. - **Updated Code**: Introduced custom error handling through `ParserError`, which provides more informative error messages. - **Reason**: Improves the debugging process by providing clear, context-specific error messages that help identify issues more quickly. - **Improvement**: Enhances the robustness of the application by clearly communicating problems during execution, which is crucial for both development and production environments.

### CODE REVIEW

**Comment by gto90** [comment]
@BadNintendo , thank yo for your contribution to this project.  It is most appreciated!  I am presently tied up with other projects but will be able to thoroughly review this, including validating that the Rosetta CLI tests continue to pass once I get clear.  I will finish reviewing this after May 20th.

**Review by gto90 — APPROVED** [review]
ACK

Thank you for your kind contribution @BadNintendo

**Review by ycagel — APPROVED** [review]
cACK. Thank you @BadNintendo!

**Review by JaredTate — APPROVED** [review]
cACK. Thank you very much for your work on this & contribution!

**Pull request merged**
